# Cloud Build configuration for FERPA Feedback Pipeline
# Builds Docker image, pushes to Artifact Registry, and deploys to Cloud Run
#
# Required substitutions:
#   _REGION: GCP region for deployment (e.g., us-central1)
#
# Environment variables set at build time:
#   PROJECT_ID: Automatically set by Cloud Build
#
# Usage:
#   gcloud builds submit --config cloudbuild.yaml \
#     --substitutions=_REGION=us-central1

# Timeout for entire build (60 minutes for large dependencies)
timeout: '3600s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Substitution variables with defaults
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'ferpa-gdrive-processor'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'
  _MEMORY: '2Gi'
  _CPU: '4'
  _TIMEOUT: '3600s'

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/ferpa-pipeline/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/ferpa-pipeline/${_SERVICE_NAME}:latest'
      - '.'

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/ferpa-pipeline/${_SERVICE_NAME}'
    waitFor:
      - 'build'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/ferpa-pipeline/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--timeout'
      - '${_TIMEOUT}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--no-allow-unauthenticated'
      - '--service-account'
      - 'ferpa-gdrive-processor@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'K_SERVICE=${_SERVICE_NAME}'
    waitFor:
      - 'push'

# Images to push to Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/ferpa-pipeline/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/ferpa-pipeline/${_SERVICE_NAME}:latest'
